apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - librefang-namespace.yaml
  - mock-kong.yaml
  - test-secret.yaml
images:
  - name: ghcr.io/whatnick/tcg-proxy-lab
    newName: tcg-proxy-lab
    newTag: kind
patches:
  - target:
      kind: Deployment
      name: tcg-proxy-lab
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Never
