apiVersion: v1
kind: Service
metadata:
  name: tcg-proxy-lab
  labels:
    app.kubernetes.io/name: tcg-proxy-lab
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tcg-proxy-lab
  ports:
    - name: http
      port: 80
      targetPort: http
